parameters:
    database_driver: pdo_mysql
    database_host: symfony2
    database_port: null
    database_name: symfony
    database_user: root
    database_password: oferofer770
    mailer_transport: gmail
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: smtp.gmail.com
    mailer_user: ofer@goldbarventures.com
    mailer_password: 
    locale: en
    secret: 088b2b79a694fbcd4a6446c0045653aed0893aa7
    database_path: null